// Code generated by GoGamePlug DO NOT EDIT.

package R

var (
	MAP     = newMap_zdcalwbmuazwbchf()
	RAW     = newRaw_4dxrwyglu8r023hy()
	AUDIO   = newAudio_09gd8xhh5iku593z()
	IMAGE   = newImage_bbl0j6t80hwigdyp()
	SHADER  = newShader_q2avi174kinyk0n1()
	SPRITE  = newSprite_o2kjesc3r0c16ldn()
	TILESET = newTileset_eba7xjb74ilfpdgz()
	CLASS   = newClass_3qg3n06oomii5zr2()
	LAYER   = newLayer_p9jg4pjdrrwyxmoc()
	OBJECT  = newObject_res1tfjofj6xbv0e()
	PROP    = newProp_tdlqkmgqsriscah4()
	MAIN    = newMain_ox5853nlympjbbqd()
)

type map_zdcalwbmuazwbchf struct {
	LEVEL1 string
}

func newMap_zdcalwbmuazwbchf() *map_zdcalwbmuazwbchf {
	return &map_zdcalwbmuazwbchf{LEVEL1: "res/map/level1.tmx"}
}

type raw_4dxrwyglu8r023hy struct {
}

func newRaw_4dxrwyglu8r023hy() *raw_4dxrwyglu8r023hy {
	return &raw_4dxrwyglu8r023hy{}
}

type audio_09gd8xhh5iku593z struct {
}

func newAudio_09gd8xhh5iku593z() *audio_09gd8xhh5iku593z {
	return &audio_09gd8xhh5iku593z{}
}

type image_bbl0j6t80hwigdyp struct {
	BG   string
	MAIN string
}

func newImage_bbl0j6t80hwigdyp() *image_bbl0j6t80hwigdyp {
	return &image_bbl0j6t80hwigdyp{BG: "res/image/bg.png", MAIN: "res/image/main.png"}
}

type shader_q2avi174kinyk0n1 struct {
}

func newShader_q2avi174kinyk0n1() *shader_q2avi174kinyk0n1 {
	return &shader_q2avi174kinyk0n1{}
}

type sprite_o2kjesc3r0c16ldn struct {
	MAIN string
}

func newSprite_o2kjesc3r0c16ldn() *sprite_o2kjesc3r0c16ldn {
	return &sprite_o2kjesc3r0c16ldn{MAIN: "res/sprite/main.json"}
}

type tileset_eba7xjb74ilfpdgz struct {
}

func newTileset_eba7xjb74ilfpdgz() *tileset_eba7xjb74ilfpdgz {
	return &tileset_eba7xjb74ilfpdgz{}
}

type class_3qg3n06oomii5zr2 struct {
	LAND   string
	SLOPE  string
	PLAYER string
}

func newClass_3qg3n06oomii5zr2() *class_3qg3n06oomii5zr2 {
	return &class_3qg3n06oomii5zr2{LAND: "land", SLOPE: "slope", PLAYER: "player"}
}

type layer_p9jg4pjdrrwyxmoc struct {
	COLLISION string
	BG        string
	PLAYER    string
}

func newLayer_p9jg4pjdrrwyxmoc() *layer_p9jg4pjdrrwyxmoc {
	return &layer_p9jg4pjdrrwyxmoc{COLLISION: "collision", BG: "bg", PLAYER: "player"}
}

type object_res1tfjofj6xbv0e struct {
	PLAYER1 string
	PLAYER2 string
}

func newObject_res1tfjofj6xbv0e() *object_res1tfjofj6xbv0e {
	return &object_res1tfjofj6xbv0e{PLAYER1: "player1", PLAYER2: "player2"}
}

type prop_tdlqkmgqsriscah4 struct {
	LEFT    string
	CONTROL string
	RIGHT   string
	HEIGHT  string
}

func newProp_tdlqkmgqsriscah4() *prop_tdlqkmgqsriscah4 {
	return &prop_tdlqkmgqsriscah4{LEFT: "left", CONTROL: "control", RIGHT: "right", HEIGHT: "height"}
}

type main_ox5853nlympjbbqd struct {
	PLAYER *player_cn0ayj9wcba5fo1i
	ITEM   *item_znvt0eozljfm4xvx
}

func newMain_ox5853nlympjbbqd() *main_ox5853nlympjbbqd {
	return &main_ox5853nlympjbbqd{PLAYER: newPlayer_cn0ayj9wcba5fo1i(), ITEM: newItem_znvt0eozljfm4xvx()}
}

type player_cn0ayj9wcba5fo1i struct {
	AIR    *air_fhahffw9eqm58scg
	ATTACK *attack_6z07xis98549e92v
	HIT    *hit_c66rf2mkvfjj9o2s
	STAND  *stand_kpug5fr32pj2n421
}

func newPlayer_cn0ayj9wcba5fo1i() *player_cn0ayj9wcba5fo1i {
	return &player_cn0ayj9wcba5fo1i{AIR: newAir_fhahffw9eqm58scg(), ATTACK: newAttack_6z07xis98549e92v(), HIT: newHit_c66rf2mkvfjj9o2s(), STAND: newStand_kpug5fr32pj2n421()}
}

type air_fhahffw9eqm58scg struct {
	DOWN  string
	FIST  string
	FOOT  string
	SKILL string
	UP    string
}

func newAir_fhahffw9eqm58scg() *air_fhahffw9eqm58scg {
	return &air_fhahffw9eqm58scg{DOWN: "player/air/down", FIST: "player/air/fist", FOOT: "player/air/foot", SKILL: "player/air/skill", UP: "player/air/up"}
}

type attack_6z07xis98549e92v struct {
	ATTACK1 string
	ATTACK2 string
	ATTACK3 string
	BACK    string
	KNIFE   string
	STICK   string
}

func newAttack_6z07xis98549e92v() *attack_6z07xis98549e92v {
	return &attack_6z07xis98549e92v{ATTACK1: "player/attack/attack1", ATTACK2: "player/attack/attack2", ATTACK3: "player/attack/attack3", BACK: "player/attack/back", KNIFE: "player/attack/knife", STICK: "player/attack/stick"}
}

type hit_c66rf2mkvfjj9o2s struct {
	FLY    string
	LAND   string
	NORMAL string
}

func newHit_c66rf2mkvfjj9o2s() *hit_c66rf2mkvfjj9o2s {
	return &hit_c66rf2mkvfjj9o2s{FLY: "player/hit/fly", LAND: "player/hit/land", NORMAL: "player/hit/normal"}
}

type stand_kpug5fr32pj2n421 struct {
	KNIFE  string
	NORMAL string
	STICK  string
}

func newStand_kpug5fr32pj2n421() *stand_kpug5fr32pj2n421 {
	return &stand_kpug5fr32pj2n421{KNIFE: "player/stand/knife", NORMAL: "player/stand/normal", STICK: "player/stand/stick"}
}

type item_znvt0eozljfm4xvx struct {
	KNIFE string
	STICK string
}

func newItem_znvt0eozljfm4xvx() *item_znvt0eozljfm4xvx {
	return &item_znvt0eozljfm4xvx{KNIFE: "item/knife", STICK: "item/stick"}
}
